/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jingt
 */
public class Admin_CusPrintReceipt extends javax.swing.JFrame {

    public Admin_CusPrintReceipt() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }
    
    /**
     * Creates new form Admin_CusPrintReceipt
     */
    public Admin_CusPrintReceipt(String AdmName, String TransID, String BookingID, String CarID, String UserID, String Name, Date TransDate, String PaymentMethod, float TotalPrice, float Price, int Duration) {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd    HH:mm:ss");
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
        lTransID.setText(TransID);
        lTransDate.setText(sdf.format(TransDate));
        lCusID.setText(UserID);
        lName.setText(Name);
        lBookingID.setText(BookingID);
        lCarID.setText(CarID);
        lPaymentMethod.setText(PaymentMethod);
        lTransAmount.setText("" + TotalPrice);
        lPaymentAmount.setText("" + TotalPrice);
        lTotalAmount.setText("" + TotalPrice);
        lPrice.setText(Float.toString(Price));
        lDuration.setText("" + Duration);
        lAdminName.setText(AdmName);
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lCusID = new javax.swing.JLabel();
        CustomerID = new javax.swing.JLabel();
        CusName = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        TransactionID = new javax.swing.JLabel();
        TransactionDate = new javax.swing.JLabel();
        lTransID = new javax.swing.JLabel();
        lTransDate = new javax.swing.JLabel();
        BookingDetails = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Colon = new javax.swing.JLabel();
        BookingID = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CarID = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        PricePerDay = new javax.swing.JLabel();
        TransactionAmount = new javax.swing.JLabel();
        lBookingID = new javax.swing.JLabel();
        lCarID = new javax.swing.JLabel();
        lDuration = new javax.swing.JLabel();
        lPrice = new javax.swing.JLabel();
        RM3 = new javax.swing.JLabel();
        lTransAmount = new javax.swing.JLabel();
        PaymentDetails = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        PaymentAmount = new javax.swing.JLabel();
        lPaymentMethod = new javax.swing.JLabel();
        PaymentMethod = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        RM1 = new javax.swing.JLabel();
        lPaymentAmount = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        TotalAmountPaid = new javax.swing.JLabel();
        lTotalAmount = new javax.swing.JLabel();
        RM2 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        PaymentReceipt = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        Address3 = new javax.swing.JLabel();
        Address4 = new javax.swing.JLabel();
        RM4 = new javax.swing.JLabel();
        bExporttoPDF = new javax.swing.JButton();
        bBacktoMenu = new javax.swing.JButton();
        lAdminName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 720));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lCusID.setText(" ");

        CustomerID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CustomerID.setText("CUSTOMER ID");

        CusName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CusName.setText("CUSTOMER NAME        :");

        lName.setText(" ");

        TransactionID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransactionID.setText("TRANSACTION ID   :");

        TransactionDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransactionDate.setText("TRANSACTION DATE   :");

        lTransID.setText(" ");

        lTransDate.setText(" ");

        BookingDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BookingDetails.setForeground(new java.awt.Color(153, 153, 153));
        BookingDetails.setText("Booking Details");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        Colon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Colon.setText(":");

        BookingID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BookingID.setText("BOOKING ID");

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        CarID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CarID.setText("CAR ID");

        Duration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Duration.setText("DURATION");

        PricePerDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PricePerDay.setText("PRICE PER DAY");

        TransactionAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransactionAmount.setText("TRANSACTION AMOUNT");

        lBookingID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lBookingID.setText(" ");
        lBookingID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lCarID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCarID.setText(" ");
        lCarID.setFocusable(false);
        lCarID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDuration.setText(" ");
        lDuration.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPrice.setText(" ");
        lPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RM3.setText("RM");

        lTransAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTransAmount.setText("   ");
        lTransAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PaymentDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        PaymentDetails.setForeground(new java.awt.Color(153, 153, 153));
        PaymentDetails.setText("Payment Details");

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        PaymentAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PaymentAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaymentAmount.setText("PAYMENT AMOUNT");
        PaymentAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lPaymentMethod.setText(" ");

        PaymentMethod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PaymentMethod.setText("PAYMENT METHOD");

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));

        RM1.setText("RM");

        lPaymentAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPaymentAmount.setText("   ");
        lPaymentAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));

        TotalAmountPaid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalAmountPaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalAmountPaid.setText("Total Amount Paid :");
        TotalAmountPaid.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTotalAmount.setText("   ");
        lTotalAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RM2.setText("RM");

        Message.setText("Please keep this copy for your own records");

        PaymentReceipt.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 25)); // NOI18N
        PaymentReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaymentReceipt.setText("Payment Receipt");
        PaymentReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Address1.setText("JC Car Rental Centre");

        Address2.setText("2, Lebuhraya Bukit Jalil");

        Address3.setText("Kuala Lumpur, 57000,");

        Address4.setText("Malaysia");

        RM4.setText("RM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BookingID)
                        .addGap(150, 150, 150)
                        .addComponent(CarID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Duration)
                        .addGap(237, 237, 237)
                        .addComponent(PricePerDay)
                        .addGap(66, 66, 66)
                        .addComponent(TransactionAmount)
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Colon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lCusID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TransactionID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lTransID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransactionDate)
                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lTransDate, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(lName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalAmountPaid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RM4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaymentReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(PaymentMethod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PaymentAmount)
                                .addGap(56, 56, 56))
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Address3)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Address2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Address1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(Address4)))
                                    .addComponent(BookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 956, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaymentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addComponent(lCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(RM2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(RM3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lTransAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PaymentReceipt)
                .addGap(18, 18, 18)
                .addComponent(Address1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransactionID)
                    .addComponent(lTransID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransactionDate)
                    .addComponent(lTransDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerID)
                    .addComponent(lName)
                    .addComponent(Colon)
                    .addComponent(lCusID)
                    .addComponent(CusName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingID)
                    .addComponent(CarID)
                    .addComponent(Duration)
                    .addComponent(PricePerDay)
                    .addComponent(TransactionAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lBookingID)
                        .addComponent(lCarID))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RM3)
                        .addComponent(lTransAmount))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lPrice)
                        .addComponent(RM2)
                        .addComponent(lDuration)))
                .addGap(21, 21, 21)
                .addComponent(PaymentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentMethod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPaymentMethod)
                    .addComponent(lPaymentAmount)
                    .addComponent(RM1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RM4)
                    .addComponent(lTotalAmount)
                    .addComponent(Message))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bExporttoPDF.setText("Export to PDF");
        bExporttoPDF.setFocusPainted(false);
        bExporttoPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExporttoPDFActionPerformed(evt);
            }
        });

        bBacktoMenu.setText("Back to Menu");
        bBacktoMenu.setFocusPainted(false);
        bBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBacktoMenuActionPerformed(evt);
            }
        });

        lAdminName.setText(" ");

        jLabel1.setText("By: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 769, Short.MAX_VALUE)
                .addComponent(bExporttoPDF)
                .addGap(18, 18, 18)
                .addComponent(bBacktoMenu)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(571, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lAdminName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bBacktoMenu)
                        .addComponent(bExporttoPDF)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExporttoPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExporttoPDFActionPerformed
        printReceipt(jPanel5);
    }//GEN-LAST:event_bExporttoPDFActionPerformed

    private void bBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBacktoMenuActionPerformed
        String AdminName = lAdminName.getText();
        this.setVisible(false);
        new AdminMenu(AdminName).setVisible(true);
    }//GEN-LAST:event_bBacktoMenuActionPerformed

    private void printReceipt(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print Receipt");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX(),
                        pageFormat.getImageableY() + pageFormat.getImageableHeight() / 2 - jPanel5.getHeight() / 2);
                graphics2D.scale(0.75, 0.75);
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        if (returningResult) {
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_CusPrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_CusPrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_CusPrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_CusPrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_CusPrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Address3;
    private javax.swing.JLabel Address4;
    private javax.swing.JLabel BookingDetails;
    private javax.swing.JLabel BookingID;
    private javax.swing.JLabel CarID;
    private javax.swing.JLabel Colon;
    private javax.swing.JLabel CusName;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel PaymentAmount;
    private javax.swing.JLabel PaymentDetails;
    private javax.swing.JLabel PaymentMethod;
    private javax.swing.JLabel PaymentReceipt;
    private javax.swing.JLabel PricePerDay;
    private javax.swing.JLabel RM1;
    private javax.swing.JLabel RM2;
    private javax.swing.JLabel RM3;
    private javax.swing.JLabel RM4;
    private javax.swing.JLabel TotalAmountPaid;
    private javax.swing.JLabel TransactionAmount;
    private javax.swing.JLabel TransactionDate;
    private javax.swing.JLabel TransactionID;
    private javax.swing.JButton bBacktoMenu;
    private javax.swing.JButton bExporttoPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lAdminName;
    private javax.swing.JLabel lBookingID;
    private javax.swing.JLabel lCarID;
    private javax.swing.JLabel lCusID;
    private javax.swing.JLabel lDuration;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPaymentAmount;
    private javax.swing.JLabel lPaymentMethod;
    private javax.swing.JLabel lPrice;
    private javax.swing.JLabel lTotalAmount;
    private javax.swing.JLabel lTransAmount;
    private javax.swing.JLabel lTransDate;
    private javax.swing.JLabel lTransID;
    // End of variables declaration//GEN-END:variables
}
