/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jingt
 */
public class Admin_ManageCusBooking extends javax.swing.JFrame {

    static Transaction trans;

    /**
     * Creates new form Admin_ManageCusBooking
     */
    public Admin_ManageCusBooking() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }
    
    public Admin_ManageCusBooking(String Name) {
        initComponents();
        lName.setText(Name);
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        tfBookingID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        bBacktoMenu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bShowAllBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingHistoryTable = new javax.swing.JTable();
        cbReturnTime = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbCollectionTime = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCusID = new javax.swing.JTextField();
        bCancel = new javax.swing.JButton();
        tfTotalPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfDuration = new javax.swing.JTextField();
        tfCarID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcStartDate = new com.toedter.calendar.JDateChooser();
        jdcEndDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(235, 232, 252));

        tfBookingID.setEnabled(false);

        jLabel13.setText("Booking ID");

        lName.setText("1");

        bBacktoMenu.setText("Back to Menu");
        bBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBacktoMenuActionPerformed(evt);
            }
        });

        jLabel11.setText("Hi, Admin");

        bShowAllBooking.setText("Show All Records");
        bShowAllBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowAllBookingActionPerformed(evt);
            }
        });

        BookingHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Name", "Car ID", "Start Date", "Collect Time", "End Date", "Return Date", "Duration", "Status", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BookingHistoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingHistoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookingHistoryTable);

        cbReturnTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        jLabel12.setText("Customer ID");

        jLabel9.setText("Return Time");

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel1.setText("Customer Booking Details");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setText("End Date");

        cbCollectionTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        jLabel7.setText("Collection Time");

        jLabel6.setText("Start Date");

        tfName.setEnabled(false);

        jLabel3.setText("Name");

        tfCusID.setEnabled(false);

        bCancel.setText("Cancel Booking");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        tfTotalPrice.setEnabled(false);

        jLabel14.setText("Total Price");

        tfDuration.setEnabled(false);

        tfCarID.setEnabled(false);

        jLabel10.setText("Duration");

        jLabel2.setText("Car ID");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(bShowAllBooking)
                                .addGap(18, 18, 18)
                                .addComponent(bCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bBacktoMenu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfCusID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCarID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName)
                                    .addComponent(tfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbReturnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                                    .addComponent(tfDuration)
                                                    .addComponent(jdcStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbCollectionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jdcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(61, 61, 61)))
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(lName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jdcStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbCollectionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbReturnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bShowAllBooking)
                    .addComponent(bBacktoMenu)
                    .addComponent(bCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBacktoMenuActionPerformed
        // TODO add your handling code here:
        String Name = lName.getText();
        this.dispose();
        new AdminMenu(Name).setVisible(true);
    }//GEN-LAST:event_bBacktoMenuActionPerformed

    private void bShowAllBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowAllBookingActionPerformed
        // TODO add your handling code here:
        File f = new File("Bookings.txt");

        DefaultTableModel model = (DefaultTableModel) BookingHistoryTable.getModel();
        model.setRowCount(0);
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String line;
            while ((line = br.readLine()) != null) {
                String[] recLine = line.split(";");
                String BookingID = recLine[1];
                String UserID = recLine[2];
                String Name = recLine[3];
                String CarID = recLine[4];
                String StartDate = recLine[5];
                String CollectionTime = recLine[6];
                String EndDate = recLine[7];
                String ReturnTime = recLine[8];
                String Duration = recLine[9];
                String Status = recLine[10];
                String Price = recLine[11];

                Object[] row = {BookingID, UserID, Name, CarID, StartDate, CollectionTime, EndDate,
                    ReturnTime, Duration, Status, Price};
                model.addRow(row);
            }
        } catch (Exception x) {

        }
    }//GEN-LAST:event_bShowAllBookingActionPerformed

    private void BookingHistoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingHistoryTableMouseClicked
        try {
            // TODO add your handling code here:
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            int i = BookingHistoryTable.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) BookingHistoryTable.getModel();
            tfBookingID.setText(model.getValueAt(i, 0).toString());
            tfCusID.setText(model.getValueAt(i, 1).toString());
            String CusID = tfCusID.getText();
            System.out.println(CusID);
            tfName.setText(model.getValueAt(i, 2).toString());
            tfCarID.setText(model.getValueAt(i, 3).toString());
            jdcStartDate.setDate(sdf.parse(model.getValueAt(i, 4).toString()));

            String comboCollectionTime = model.getValueAt(i, 5).toString();
            for (int index = 0; index < cbCollectionTime.getItemCount(); index++) {
                if (cbCollectionTime.getItemAt(index).equalsIgnoreCase(comboCollectionTime)) {
                    cbCollectionTime.setSelectedIndex(index);
                }
            }

            jdcEndDate.setDate(sdf.parse(model.getValueAt(i, 6).toString()));
            String comboReturnTime = model.getValueAt(i, 7).toString();
            for (int index = 0; index < cbReturnTime.getItemCount(); index++) {
                if (cbReturnTime.getItemAt(index).equalsIgnoreCase(comboReturnTime)) {
                    cbReturnTime.setSelectedIndex(index);
                }
            }
            tfDuration.setText(model.getValueAt(i, 8).toString());
            tfTotalPrice.setText(model.getValueAt(i, 10).toString());

        } catch (ParseException ex) {
            Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BookingHistoryTableMouseClicked

    private void ModifyBookingStatus() {
        try {
            File file = new File("Bookings.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            String BookingID = tfBookingID.getText();
            String[] rec;
            String StatusOld, StatusNew;
            Object[] allRec = br.lines().toArray();
            for (int i = 0; i < allRec.length; i++) {
                rec = allRec[i].toString().trim().split(";");
                if (BookingID.equalsIgnoreCase(rec[1])) {
                    StatusOld = rec[10];
                    StatusNew = "Cancelled";
                    rec[10] = StatusNew;
                    String newrec = "";
                    for (int j = 0; j < rec.length; j++) {
                        newrec = newrec + rec[j] + ";";
                    }
                    allRec[i] = newrec;
                }
            }
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            for (int i = 0; i < allRec.length; i++) {
                bw.write(allRec[i] + "\n");
            }
            bw.close();
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ModifyCarStatus() throws FileNotFoundException, IOException {
        File file = new File("Car Info.txt");

        BufferedReader br = new BufferedReader(new FileReader(file));
        String CarID = tfCarID.getText();
        String[] rec;
        String AvailableOld, AvailableNew;
        Object[] allRec = br.lines().toArray();
        for (int i = 0; i < allRec.length; i++) {
            rec = allRec[i].toString().trim().split(";");
            if (CarID.equalsIgnoreCase(rec[1])) {
                AvailableOld = rec[11];
                AvailableNew = "Yes";
                rec[11] = AvailableNew;
                String newrec = "";
                for (int j = 0; j < rec.length; j++) {
                    newrec = newrec + rec[j] + ";";
                }
                allRec[i] = newrec;
            }
        }
        BufferedWriter bw = new BufferedWriter(new FileWriter(file));
        for (int i = 0; i < allRec.length; i++) {
            bw.write(allRec[i] + "\n");
        }
        bw.close();
        br.close();
    }
    
    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed

        Transaction transInfo = new Transaction();
        String BookingID = tfBookingID.getText().trim();
        String CusID = tfCusID.getText().trim();
        String CarID = tfCarID.getText().trim();
        //bookingInfo.setName(tfName.getText().trim());

        int showConfirmDialog = JOptionPane.showConfirmDialog(null, BookingID + " of Customer " + CusID + " with Booked Car " + CarID + " will be deleted"
            + "\nAre you sure to continue?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            try {
                trans = new Transaction(transInfo.getID(), transInfo.getTransID(),BookingID, CusID,transInfo.getDuration(), transInfo.getTotalPrice(),transInfo.getPaymentMethod(), transInfo.getTransDate());
                trans.Delete();
                ModifyBookingStatus();
                ModifyCarStatus();
                JOptionPane.showMessageDialog(null, "Customer Booking Has Been Cancel");
            } catch (IOException ex) {
                Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ManageCusBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ManageCusBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookingHistoryTable;
    private javax.swing.JButton bBacktoMenu;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bShowAllBooking;
    private javax.swing.JComboBox<String> cbCollectionTime;
    private javax.swing.JComboBox<String> cbReturnTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcEndDate;
    private com.toedter.calendar.JDateChooser jdcStartDate;
    private javax.swing.JLabel lName;
    private javax.swing.JTextField tfBookingID;
    private javax.swing.JTextField tfCarID;
    private javax.swing.JTextField tfCusID;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfTotalPrice;
    // End of variables declaration//GEN-END:variables
}
