/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author jingt
 */
public class Cus_Profile extends javax.swing.JFrame {

    static Customer customer;

    /**
     * Creates new form Cus_Profile
     */
    public Cus_Profile() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }

    public Cus_Profile(String UserID, String Name, String ICNum, String ContactNum, String Email, String Password) {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
        tfUserID.setText(UserID);
        tfName.setText(Name);
        tfIC.setText(ICNum);
        tfContactNum.setText(ContactNum);
        tfEmail.setText(Email);
        pfPassword.setText(Password);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        tfIC = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfUserID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lCusID = new javax.swing.JLabel();
        SignOutButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ChangeContactButton = new javax.swing.JButton();
        ChangeEmailButton = new javax.swing.JButton();
        ChangePasswordButton = new javax.swing.JButton();
        pfPassword = new javax.swing.JPasswordField();
        tfContactNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lCusName = new javax.swing.JLabel();
        EmailValidation = new javax.swing.JLabel();
        NumberValidation = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 600));

        jPanel10.setBackground(new java.awt.Color(235, 232, 252));
        jPanel10.setPreferredSize(new java.awt.Dimension(1128, 600));

        tfIC.setEnabled(false);

        tfName.setEnabled(false);

        tfUserID.setEnabled(false);

        jLabel10.setText(":");

        lCusID.setText("User ID");

        SignOutButton.setText("Sign Out");
        SignOutButton.setFocusPainted(false);
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });

        BackButton.setText("< Back");
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ChangeContactButton.setText("Change");
        ChangeContactButton.setFocusPainted(false);
        ChangeContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeContactButtonActionPerformed(evt);
            }
        });

        ChangeEmailButton.setText("Change");
        ChangeEmailButton.setFocusPainted(false);
        ChangeEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeEmailButtonActionPerformed(evt);
            }
        });

        ChangePasswordButton.setText("Change");
        ChangePasswordButton.setFocusPainted(false);
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        pfPassword.setText("          ");
        pfPassword.setEnabled(false);

        jLabel3.setText("IC Number");

        jLabel2.setText("Contact Number");

        jLabel1.setText("Email Address");

        lCusName.setText("Name");

        EmailValidation.setText(" ");

        NumberValidation.setText(" ");

        jLabel9.setText(":");

        jLabel8.setText(":");

        jLabel7.setText(":");

        jLabel6.setText(":");

        jLabel5.setText(":");

        jLabel4.setText("Password         ");

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Customer Profile");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lCusName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail)
                            .addComponent(pfPassword)
                            .addComponent(tfIC)
                            .addComponent(tfName)
                            .addComponent(tfUserID)
                            .addComponent(EmailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChangePasswordButton)
                            .addComponent(ChangeEmailButton)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(NumberValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(tfContactNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeContactButton)))))
                .addGap(561, 561, 561))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignOutButton)
                .addGap(267, 267, 267))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(SignOutButton))
                .addGap(36, 36, 36)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCusID)
                    .addComponent(jLabel5)
                    .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCusName)
                    .addComponent(jLabel7)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangePasswordButton))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(tfIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeEmailButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(tfContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeContactButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        this.setVisible(false);
        new UserLoginMenu().setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        String name = tfName.getText();
        String userid = tfUserID.getText();
        this.setVisible(false);
        new CustomerMenu(name, userid).setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ChangeContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeContactButtonActionPerformed
        try {
            Customer cusInfo = new Customer();
            File cusfile = new File("Customer.txt");
            String CusID = tfUserID.getText().trim();
            String Name = tfName.getText().trim();
            String ICNum = tfIC.getText().trim();
            String ContactNum = tfContactNum.getText().trim();
            String Email = tfEmail.getText().trim();
            String Password = pfPassword.getText().trim();
            cusInfo.setPassword(Password);
            BufferedReader brcusfile = new BufferedReader(new FileReader(cusfile));
            String linerec;
            while ((linerec = brcusfile.readLine())!=null) {
                String[] recLine = linerec.split(";");
                if(CusID.equals(recLine[1])) {
                    cusInfo.setID(Integer.parseInt(recLine[0]));
                }
            }

            if (!Email.isEmpty()) {
                if (Customer.isEmailValid(Email)) {
                    EmailValidation.setText("");
                } else {
                    Email = null;
                    EmailValidation.setText("Invalid Email");
                }
            } else {
                Email = null;
                EmailValidation.setText("Enter Email");
            }

            if (!ContactNum.isEmpty()) {
                if (ContactNum.length() == 10 || ContactNum.length() == 11) {
                    if (Admin.isContactValid(ContactNum)) {
                        NumberValidation.setText("");
                    } else {
                        ContactNum = null;
                        NumberValidation.setText("Enter Integer");
                    }
                } else {
                    ContactNum = null;
                    NumberValidation.setText("Enter 10 or 11 Integer Only");
                }
            } else {
                ContactNum = null;
                NumberValidation.setText("Enter Contact Number");
            }

            if (Email != null && ContactNum != null) {
                customer = new Customer(cusInfo.getID(), CusID, Name, ICNum, ContactNum, Email, cusInfo.getPassword(), cusInfo.getUser_Type());
                System.out.println(customer.toString());
                customer.Update();
                JOptionPane.showMessageDialog(null, "Update Successfully");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cus_Profile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cus_Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChangeContactButtonActionPerformed

    private void ChangeEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeEmailButtonActionPerformed
        try {
            Customer cusInfo = new Customer();
            File cusfile = new File("Customer.txt");
            String CusID = tfUserID.getText().trim();
            String Name = tfName.getText().trim();
            String ICNum = tfIC.getText().trim();
            String ContactNum = tfContactNum.getText().trim();
            String Email = tfEmail.getText().trim();
            String Password = pfPassword.getText().trim();
            cusInfo.setPassword(Password);
            BufferedReader brcusfile = new BufferedReader(new FileReader(cusfile));
            String linerec;
            while ((linerec = brcusfile.readLine())!=null) {
                String[] recLine = linerec.split(";");
                if(CusID.equals(recLine[1])) {
                    cusInfo.setID(Integer.parseInt(recLine[0]));
                }
            }
            if (!Email.isEmpty()) {
                if (Customer.isEmailValid(Email)) {
                    EmailValidation.setText("");
                } else {
                    Email = null;
                    EmailValidation.setText("Invalid Email");
                }
            } else {
                Email = null;
                EmailValidation.setText("Enter Email");
            }

            if (!ContactNum.isEmpty()) {
                if (ContactNum.length() == 10 || ContactNum.length() == 11) {
                    if (Admin.isContactValid(ContactNum)) {
                        NumberValidation.setText("");
                    } else {
                        ContactNum = null;
                        NumberValidation.setText("Enter Integer");
                    }
                } else {
                    ContactNum = null;
                    NumberValidation.setText("Enter 10 or 11 Integer Only");
                }
            } else {
                ContactNum = null;
                NumberValidation.setText("Enter Contact Number");
            }

            if (Email != null && ContactNum != null) {
                customer = new Customer(cusInfo.getID(), CusID, Name, ICNum, ContactNum, Email, cusInfo.getPassword(), cusInfo.getUser_Type());
                System.out.println(customer.toString());
                customer.Update();
                JOptionPane.showMessageDialog(null, "Update Successfully");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cus_Profile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cus_Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChangeEmailButtonActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        String userid = tfUserID.getText();
        String name = tfName.getText();
        this.setVisible(false);
        new Cus_ChangePassword(name, userid).setVisible(true);
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ChangeContactButton;
    private javax.swing.JButton ChangeEmailButton;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JLabel EmailValidation;
    private javax.swing.JLabel NumberValidation;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel lCusID;
    private javax.swing.JLabel lCusName;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfContactNum;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfIC;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUserID;
    // End of variables declaration//GEN-END:variables
}
