/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jingt
 */
public class Cus_MakeBooking extends javax.swing.JFrame {

    static Booking bookings;

        
    /**
     * Creates new form Cus_MakeBooking
     */
    public Cus_MakeBooking() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }
    
    public Cus_MakeBooking(String UserID, String Name, String Email, String Contact) {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
        InsertFileDatatoJTable();
        tfUserID.setText(UserID);
        tfName.setText(Name);
        tfNumber.setText(Contact);
        tfEmail.setText(Email);
    }
    
    private void InsertFileDatatoJTable() {
        try {
            File file = new File("Car Info.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel) CarInfoTable.getModel();
            // get lines from txt file
            //Object[] tableLines = br.lines().toArray();
            String line;
            while ((line = br.readLine()) != null) {
                String[] carLine = line.split(";");
                String CarID = carLine[1];
                String CarPlate = carLine[2];
                String Year = carLine[3];
                String Passenger_Capacity = carLine[4];
                String Model = carLine[5];
                String Colour = carLine[6];
                String Type = carLine[7];
                String Transmission = carLine[8];
                String Price = carLine[9];
                String Brand = carLine[10];
                String Avaibility = carLine[11];

                if (Avaibility.equals("Yes")) {
                    Object[] row = {CarID, CarPlate, Year, Passenger_Capacity, Model,
                        Colour, Type, Transmission, Price, Brand};
                    model.addRow(row);
                }
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        } catch (IOException ex) {
            Logger.getLogger(Cus_MakeBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcStartDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        tfUserID = new javax.swing.JTextField();
        tfBookingID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarInfoTable = new javax.swing.JTable();
        tfcarid = new javax.swing.JTextField();
        tfTotalPrice = new javax.swing.JTextField();
        jdcEndDate = new com.toedter.calendar.JDateChooser();
        cbReturnTime = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Confirm_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cancel_Button = new javax.swing.JButton();
        cbCollectionTime = new javax.swing.JComboBox<>();
        tfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        tfDuration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 720));

        jPanel1.setBackground(new java.awt.Color(235, 232, 252));

        jLabel13.setText("Booking ID");

        jLabel10.setText("Duration");

        jLabel6.setText("Start Date");

        jLabel2.setText("Car ID");

        jLabel9.setText("Return Time");

        tfUserID.setEnabled(false);

        tfBookingID.setEnabled(false);

        CarInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Car Plate Number", "Year", "Passenger Capacity", "Model", "Colour", "Type", "Transmission", "Brand", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarInfoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarInfoTable);

        tfcarid.setEnabled(false);

        tfTotalPrice.setEnabled(false);

        cbReturnTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        jLabel3.setText("Name");

        jLabel8.setText("End Date");

        Confirm_Button.setText("Confirm");
        Confirm_Button.setFocusPainted(false);
        Confirm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_ButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Collection Time");

        Cancel_Button.setText("Cancel");
        Cancel_Button.setFocusPainted(false);
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });

        cbCollectionTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        tfEmail.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel1.setText("Car Rental Booking");

        jLabel4.setText("Contact Number");

        jLabel5.setText("Email");

        tfName.setEnabled(false);

        tfNumber.setEnabled(false);

        tfDuration.setEnabled(false);

        jLabel12.setText("Total Price");

        jLabel11.setText("Customer ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Confirm_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel_Button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13))
                    .addGap(60, 60, 60)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfUserID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfcarid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfName)
                        .addComponent(tfEmail)
                        .addComponent(tfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbReturnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCollectionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfTotalPrice)
                                .addComponent(tfDuration)
                                .addComponent(jdcStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(203, 203, 203))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(776, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Confirm_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cancel_Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jdcStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbCollectionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jdcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbReturnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(tfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tfcarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))))
                    .addGap(416, 416, 416)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarInfoTableMouseClicked
        // TODO add your handling code here:
        int i = CarInfoTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) CarInfoTable.getModel();
        tfcarid.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_CarInfoTableMouseClicked

    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        // TODO add your handling code here:
        Booking booking = new Booking();
        //        String userid = tfUserID.getText();
        //        String userName = tfName.getText();

        try {
            //Booking orders = new Booking(Integer.parseInt(recLine[0]), recLine[1], recLine[2], recLine[3], recLine[4], recLine[5], recLine[6], recLine[7], recLine[8]);
            //            tfBookingID.setText(booking.getBookingID());

            String CusID = tfUserID.getText().trim(),
            Name = tfName.getText().trim(),
            collectiontime = cbCollectionTime.getSelectedItem().toString(),
            returntime = cbReturnTime.getSelectedItem().toString(),
            CarID = tfcarid.getText().trim(),
            email = tfEmail.getText().trim(),
            ContactNum = tfNumber.getText().trim();

            booking.setCusID(CusID);
            booking.setCusName(Name);
            booking.setCarID(CarID);
            booking.setCollection_Time(collectiontime);
            booking.setReturned_Time(returntime);

            //Booking booking = new Booking(0,booking.getBookingID(),)
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.ENGLISH);
            Date startdate = this.jdcStartDate.getDate();
            Date enddate = this.jdcEndDate.getDate();
            String strstartdate = sdf.format(startdate);
            String strenddate = sdf.format(enddate);

            // Extracts string start date and end date into yyyy/MM/dd
            Date StartDate = sdf.parse(strstartdate);
            Date EndDate = sdf.parse(strenddate);

            // Date Validation
            if (Booking.DateValidation(StartDate, EndDate) == true) {
                booking.setStart_Date(startdate);
                booking.setEnd_Date(enddate);
                int Duration = booking.calculateDuration(StartDate, EndDate);
                tfDuration.setText("" + Duration);
                booking.setDuration(Duration);
                int i = CarInfoTable.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) CarInfoTable.getModel();
                float price = Float.parseFloat(model.getValueAt(i, 9).toString());
                //float TotalPrice = booking.calculateTotalPrice(Duration, price);
                float TotalPrice = booking.getDuration() * price;
                tfTotalPrice.setText("" + TotalPrice);
                booking.setTotalPrice(TotalPrice);
            } else {
                startdate = null;
                enddate = null;
            }

            if (CusID!=null && Name != null && email != null && ContactNum != null && startdate != null && enddate != null) {

                bookings = new Booking(0, booking.getBookingID(), booking.getCusID(), booking.getCusName(), booking.getCarID(), booking.getStart_Date(), booking.getCollection_Time(),
                    booking.getEnd_Date(), booking.getReturned_Time(), booking.getDuration(),
                    booking.getStatus(), booking.getTotalPrice());

                bookings.Add();
                System.out.println(bookings.toString());
                tfBookingID.setText(bookings.getBookingID());
                JOptionPane.showMessageDialog(null,"Proceed to Payment");

                this.setVisible(false);
                new Cus_MakePayment(bookings.getBookingID(), CusID, Name, CarID, bookings.getDuration(),bookings.getTotalPrice()).setVisible(true);
            }

            // Date Validation
            // Validate if StartDate is greater than End Date
            //            if (StartDate.after(EndDate)) {
                //                startdate = null;
                //                enddate = null;
                //                JOptionPane.showMessageDialog(null, "Choose End Date which is greater than Start Date");
                //            } else if (StartDate.before(EndDate)) { // Validate if StartDate is less than End Date
                //                booking.setEnd_Date(enddate);
                //                booking.setStart_Date(startdate);
                //
                ////                long diffInMillies = Math.abs(enddate.getTime() - startdate.getTime());
                ////                long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
                //                tfDuration.setText("" + booking.calculateDuration());
                //
                ////                String Duration = tfDuration.getText();
                //                // Calculate Total Price
                //                int i = CarInfoTable.getSelectedRow();
                //                DefaultTableModel model = (DefaultTableModel) CarInfoTable.getModel();
                //                float price = Float.parseFloat(model.getValueAt(i, 9).toString());
                //                booking.calculateTotalPrice(price);
                ////
                ////                long reslt = price * diff;
                //                tfTotalPrice.setText("" + booking.calculateTotalPrice(price));
                //                String totalprice = tfTotalPrice.getText();
                //            } else {
                //                JOptionPane.showMessageDialog(rootPane, "Please Choose Date");
                //            }
            // When Input Start Date and End Date are not null
            //                File tempbookings = new File("tempBookings.txt");
            //
            //                if (tempbookings.createNewFile()) {
                //                    System.out.println("File has been created.");
                //                } else {
                //                    System.out.println("File already exists.");
                //                }
            //
            //                try {
                //                    FileWriter fw = new FileWriter("tempBookings.txt");
                //                    BufferedWriter bw = new BufferedWriter(fw);
                //                    PrintWriter pw = new PrintWriter(bw);
                //                    String carid = model.getValueAt(i, 0).toString();
                //
                //                    pw.println(orders.getBookingID() + ";" + userid + ";" + userName + ";"
                    //                            + carid + ";" + orders.getStart_Date() + ";" + orders.getCollection_Time() + ";"
                    //                            + orders.getEnd_Date() + ";" + orders.getReturned_Time() + ";"
                    //                            + orders.getDuration() + ";" + "Pending" + ";" + String.valueOf(reslt) + ";"
                    //                    );
                //                    JOptionPane.showMessageDialog(null, "Proceed to Payment");
                //
                //                    pw.close();
                //                    bw.close();
                //                    fw.close();
            } catch (ParseException ex) {
                Logger.getLogger(Cus_MakeBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            //            } else if (StartDate.equals(EndDate)) { // Validate if StartDate is equal to End Date
            //                JOptionPane.showMessageDialog(null, "Do not Choose the Same Date!");
            //            }

        //            } else if (StartDate.equals(EndDate)) { // Validate if StartDate is equal to End Date
        //                JOptionPane.showMessageDialog(null, "Do not Choose the Same Date!");
        //            }
    }//GEN-LAST:event_Confirm_ButtonActionPerformed

    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String UserID = tfUserID.getText();
        String Name = tfName.getText();
        new CustomerMenu(Name, UserID).setVisible(true);
    }//GEN-LAST:event_Cancel_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_MakeBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JTable CarInfoTable;
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JComboBox<String> cbCollectionTime;
    private javax.swing.JComboBox<String> cbReturnTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcEndDate;
    private com.toedter.calendar.JDateChooser jdcStartDate;
    private javax.swing.JTextField tfBookingID;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfTotalPrice;
    private javax.swing.JTextField tfUserID;
    private javax.swing.JTextField tfcarid;
    // End of variables declaration//GEN-END:variables
}
