/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package car_rental_system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jingt
 */
public class Cus_ViewCar extends javax.swing.JFrame {

    /**
     * Creates new form Cus_ViewCar
     */
    public Cus_ViewCar() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }
    
    public Cus_ViewCar(String UserID) {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
        InsertFileDatatoJTable();
        lUserID.setText(UserID);
    }
    
    private void InsertFileDatatoJTable() {
        try {
            File file = new File("Car Info.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel) CarInfoTable.getModel();
            String line;
            while ((line = br.readLine()) != null) {
                String[] carLine = line.split(";");
                String CarID = carLine[1];
                String CarPlate = carLine[2];
                String Year = carLine[3];
                String Passenger_Capacity = carLine[4];
                String Model = carLine[5];
                String Colour = carLine[6];
                String Type = carLine[7];
                String Transmission = carLine[8];
                String Price = carLine[9];
                String Brand = carLine[10];
                String Avaibility = carLine[11];

                if (Avaibility.equals("Yes")) {
                    Object[] row = {CarID, CarPlate, Year, Passenger_Capacity, Model,
                        Colour, Type, Transmission, Price, Brand};
                    model.addRow(row);
                }
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        } catch (IOException ex) {
            Logger.getLogger(Cus_MakeBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        bSignOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarInfoTable = new javax.swing.JTable();
        lUserID = new javax.swing.JLabel();
        bBookNow = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        PaymentReceipt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 720));

        jPanel10.setBackground(new java.awt.Color(235, 232, 252));

        bSignOut.setText("Sign Out");
        bSignOut.setFocusPainted(false);
        bSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignOutActionPerformed(evt);
            }
        });

        CarInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Car Plate Number", "Year", "Passenger Capacity", "Model", "Colour", "Type", "Transmission", "Brand", "Price"
            }
        ));
        jScrollPane1.setViewportView(CarInfoTable);

        lUserID.setText(" ");

        bBookNow.setText("Book Now");
        bBookNow.setFocusPainted(false);
        bBookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookNowActionPerformed(evt);
            }
        });

        bBack.setText("< Back");
        bBack.setFocusPainted(false);
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        PaymentReceipt.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        PaymentReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaymentReceipt.setText("Car Rental Information");
        PaymentReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(1010, Short.MAX_VALUE)
                        .addComponent(bBookNow))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(bBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bSignOut))
                            .addComponent(jScrollPane1))))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PaymentReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSignOut)
                    .addComponent(bBack)
                    .addComponent(lUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentReceipt)
                .addGap(12, 12, 12)
                .addComponent(bBookNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignOutActionPerformed
        this.setVisible(false);
        new UserLoginMenu().setVisible(true);
    }//GEN-LAST:event_bSignOutActionPerformed

    private void bBookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBookNowActionPerformed
        String userid = lUserID.getText();
        File file = new File("Customer.txt");
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                String[] recLine = line.split(";");
                if (userid.equals(recLine[1])) {
                    String name = recLine[2];
                    String email = recLine[5];
                    String contact = recLine[4];
                    this.setVisible(false);
                    new Cus_MakeBooking(userid,name,email,contact).setVisible(true);
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cus_ViewCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cus_ViewCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bBookNowActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        String userid = lUserID.getText();
        File file = new File("Customer.txt");
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                String[] recLine = line.split(";");
                if (userid.equals(recLine[1])) {
                    String name = recLine[2];
                    this.setVisible(false);
                    new CustomerMenu(name, userid).setVisible(true);
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cus_ViewCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cus_ViewCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_ViewCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarInfoTable;
    private javax.swing.JLabel PaymentReceipt;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bBookNow;
    private javax.swing.JButton bSignOut;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lUserID;
    // End of variables declaration//GEN-END:variables
}
