/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.io.FileNotFoundException;

/**
 *
 * @author jingt
 */
public class Customer_Registration extends javax.swing.JFrame {

    static Customer newCus;

    /**
     * Creates new form Customer_Registration
     */
    public Customer_Registration() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        tfNumber = new javax.swing.JTextField();
        EmailValidation = new javax.swing.JLabel();
        tfCusID = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        ICValidation = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        ReenterPassword = new javax.swing.JLabel();
        ReenterpwValidation = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        NameValidation = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfICNumber = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        ICNumber = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JLabel();
        CreateAccButton = new javax.swing.JButton();
        tfPassword2 = new javax.swing.JPasswordField();
        CancelButton = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();
        NumberValidation = new javax.swing.JLabel();
        PasswordValidation = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 630));

        jPanel10.setBackground(new java.awt.Color(235, 232, 252));

        EmailValidation.setForeground(new java.awt.Color(255, 0, 0));
        EmailValidation.setText(" ");

        tfCusID.setEnabled(false);

        Name.setText("Name");

        ICValidation.setForeground(new java.awt.Color(255, 0, 0));
        ICValidation.setText(" ");

        Password.setText("Password");

        ReenterPassword.setText("Retype Password");

        ReenterpwValidation.setForeground(new java.awt.Color(255, 0, 0));
        ReenterpwValidation.setText(" ");

        Title.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("New Customer Account");

        NameValidation.setForeground(new java.awt.Color(255, 0, 0));
        NameValidation.setText(" ");

        Name1.setText("User ID");

        ICNumber.setText("IC Number");

        ContactNumber.setText("Contact Number");

        CreateAccButton.setText("Create");
        CreateAccButton.setFocusPainted(false);
        CreateAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.setFocusPainted(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        NumberValidation.setForeground(new java.awt.Color(255, 0, 0));
        NumberValidation.setText(" ");

        PasswordValidation.setForeground(new java.awt.Color(255, 0, 0));

        Email.setText("Email");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReenterPassword)
                                .addComponent(ICNumber))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfICNumber)
                                .addComponent(tfName)
                                .addComponent(tfPassword2)
                                .addComponent(tfPassword)
                                .addComponent(tfCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PasswordValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReenterpwValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ICValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ContactNumber)
                                .addComponent(Email))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(CreateAccButton)
                                    .addGap(106, 106, 106)
                                    .addComponent(CancelButton))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumberValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(199, 199, 199))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Title)
                .addGap(70, 70, 70)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1)
                    .addComponent(tfCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name)
                    .addComponent(NameValidation))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Password)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PasswordValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReenterpwValidation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ReenterPassword)
                        .addComponent(tfPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICNumber)
                    .addComponent(ICValidation))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContactNumber)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email)
                    .addComponent(EmailValidation))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAccButton)
                    .addComponent(CancelButton))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
        new UserLoginMenu().setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void CreateAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccButtonActionPerformed
        try {
            String name = this.tfName.getText().trim(),password = this.tfPassword.getText().trim(),
            reenterpw = this.tfPassword2.getText().trim(),ICNum = this.tfICNumber.getText().trim(),
            ContactNum = this.tfNumber.getText().trim(),email = this.tfEmail.getText().trim();

            // Validation
            if (!name.isEmpty()) {
                if (Customer.isNameValid(name)) {
                    NameValidation.setText("");
                } else {
                    name = null;
                    NameValidation.setText("Invalid Name");
                }
            } else {
                name = null;
                NameValidation.setText("Enter Name");
            }

            if (!password.isEmpty()) {
                PasswordValidation.setText("");
            } else {
                password = null;
                PasswordValidation.setText("Enter Password");
            }

            if (!reenterpw.isEmpty()) {
                if (reenterpw.equals(password)) {
                    ReenterpwValidation.setText("");
                } else {
                    reenterpw = null;
                    ReenterpwValidation.setText("Password Not Match");
                }
            } else {
                reenterpw = null;
                ReenterpwValidation.setText("Reenter Password");
            }

            if (!ICNum.isEmpty()) {
                if (Customer.isICValid(ICNum)) {
                    if (ICNum.length() == 12) {
                        if (Customer.isICExist(ICNum)) {
                            ICValidation.setText("");
                        } else {
                            ICNum = null;
                            ICValidation.setText("IC exists!");
                        }
                    } else {
                        ICNum = null;
                        ICValidation.setText("Invalid IC");
                    }
                } else {
                    ICNum = null;
                    ICValidation.setText("Enter IC without - or character!!");
                }
            } else {
                ICNum = null;
                ICValidation.setText("Enter IC Number without - ");
            }

            if (!ContactNum.isEmpty()) {
                if (ContactNum.length() == 10 || ContactNum.length() == 11) {
                    if (Customer.isContactValid(ContactNum)) {
                        NumberValidation.setText("");
                    } else {
                        ContactNum = null;
                        NumberValidation.setText("Enter Integer");
                    }
                } else {
                    ContactNum = null;
                    NumberValidation.setText("Enter 10 or 11 Integer Only");
                }
            } else {
                ContactNum = null;
                NumberValidation.setText("Enter Contact Number");
            }

            if (!email.isEmpty()) {
                if (Customer.isEmailValid(email)) {
                    EmailValidation.setText("");
                } else {
                    email = null;
                    EmailValidation.setText("Invalid Email");
                }
            } else {
                email = null;
                EmailValidation.setText("Enter Email");
            }

            if (name != null && password != null && reenterpw != null && ICNum != null && ContactNum != null && email != null) {
                Customer customer = new Customer();
                newCus = new Customer(0, customer.getCusID(), name, ICNum,
                    ContactNum,email, password, customer.getUser_Type());
                newCus.Add();
                tfCusID.setText(newCus.getCusID());
                JOptionPane.showMessageDialog(null, "Account Created Successfully!\nPlease Use "
                    + newCus.getCusID() + " as Login UserID");
                this.setVisible(false);
                new UserLoginMenu().setVisible(true);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Customer_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateAccButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ContactNumber;
    private javax.swing.JButton CreateAccButton;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailValidation;
    private javax.swing.JLabel ICNumber;
    private javax.swing.JLabel ICValidation;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel NameValidation;
    private javax.swing.JLabel NumberValidation;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PasswordValidation;
    private javax.swing.JLabel ReenterPassword;
    private javax.swing.JLabel ReenterpwValidation;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField tfCusID;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfICNumber;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPassword2;
    // End of variables declaration//GEN-END:variables
}
