/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rental_system;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jingt
 */
public class CustomerMenu extends javax.swing.JFrame {

    public CustomerMenu() {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen    }
    }
    
    /**
     * Creates new form CustomerMenu
     */
    public CustomerMenu(String Name, String UserID) {
        initComponents();
        this.setLocationRelativeTo(null);//Display windows at the centre of screen
        greetings.setText(Name);
        UserIDlabel.setText(UserID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        greetings = new javax.swing.JLabel();
        ViewProfile = new javax.swing.JButton();
        ViewCarDetails = new javax.swing.JButton();
        MakeBooking = new javax.swing.JButton();
        ViewBookingHistory = new javax.swing.JButton();
        ViewTransHistory = new javax.swing.JButton();
        UserIDlabel = new javax.swing.JLabel();
        bSignOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1128, 650));

        jPanel1.setBackground(new java.awt.Color(235, 232, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(1128, 624));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Menu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Welcome,");

        greetings.setText(" ");

        ViewProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewProfile.setText("View Profile");
        ViewProfile.setFocusPainted(false);
        ViewProfile.setPreferredSize(new java.awt.Dimension(231, 32));
        ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileActionPerformed(evt);
            }
        });

        ViewCarDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewCarDetails.setText("View Car Details");
        ViewCarDetails.setFocusPainted(false);
        ViewCarDetails.setPreferredSize(new java.awt.Dimension(231, 32));
        ViewCarDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCarDetailsActionPerformed(evt);
            }
        });

        MakeBooking.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MakeBooking.setText("Make Booking");
        MakeBooking.setFocusPainted(false);
        MakeBooking.setPreferredSize(new java.awt.Dimension(231, 32));
        MakeBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeBookingActionPerformed(evt);
            }
        });

        ViewBookingHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewBookingHistory.setText("View Booking History");
        ViewBookingHistory.setFocusPainted(false);
        ViewBookingHistory.setPreferredSize(new java.awt.Dimension(231, 32));
        ViewBookingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingHistoryActionPerformed(evt);
            }
        });

        ViewTransHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewTransHistory.setText("View Transaction History");
        ViewTransHistory.setFocusPainted(false);
        ViewTransHistory.setPreferredSize(new java.awt.Dimension(231, 32));
        ViewTransHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTransHistoryActionPerformed(evt);
            }
        });

        UserIDlabel.setText(" ");

        bSignOut.setText("Sign Out");
        bSignOut.setFocusPainted(false);
        bSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserIDlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(bSignOut)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewTransHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MakeBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ViewBookingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(423, 423, 423))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDlabel)
                    .addComponent(bSignOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(ViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ViewCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(MakeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ViewBookingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ViewTransHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileActionPerformed
        String userid = UserIDlabel.getText();
        File file = new File("Customer.txt");
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                String[] recLine = line.split(";");
                if (userid.equals(recLine[1])) {
                    String UserID = recLine[1];
                    String Name = recLine[2];
                    String ICNum = recLine[3];
                    String ContactNum = recLine[4];
                    String Email = recLine[5];
                    String Password = recLine[6];
                    this.setVisible(false);
                    new Cus_Profile(UserID, Name, ICNum, ContactNum, Email, Password).setVisible(true);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CustomerMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CustomerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewProfileActionPerformed

    private void ViewCarDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCarDetailsActionPerformed
        String userid = UserIDlabel.getText();
        this.setVisible(false);
        new Cus_ViewCar(userid).setVisible(true);
    }//GEN-LAST:event_ViewCarDetailsActionPerformed

    private void MakeBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeBookingActionPerformed
        File users = new File("Customer.txt");
        String userid = UserIDlabel.getText();
        try {
            FileReader fr = new FileReader(users);
            BufferedReader br = new BufferedReader(fr);
            boolean check = false;
            int i = 0;
            String line;
            while ((line = br.readLine()) != null) {
                String[] recLine = line.split(";");
                if (userid.equals(recLine[1])) {
                    String UserID = recLine[1];
                    String Name = recLine[2];
                    String Contact = recLine[4];
                    String Email = recLine[5];
                    this.setVisible(false);
                    new Cus_MakeBooking(UserID, Name, Email, Contact).setVisible(true);
                    check = true;
                    break;
                }
            }
            if (check == false) {
                JOptionPane.showMessageDialog(null, "Invalid Login Credentials! Please Register Yourself First if You Do Not Have an Account!");
            }
        } catch (HeadlessException | IOException x) {
            JOptionPane.showMessageDialog(null, "Record Not Found..." + userid);
        }
    }//GEN-LAST:event_MakeBookingActionPerformed

    private void ViewBookingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingHistoryActionPerformed
        String userid = UserIDlabel.getText();
        this.setVisible(false);
        new Cus_ViewBookingHistory(userid).setVisible(true);
    }//GEN-LAST:event_ViewBookingHistoryActionPerformed

    private void ViewTransHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTransHistoryActionPerformed
        String userid = UserIDlabel.getText();
        this.setVisible(false);
        new Cus_ViewTransactionHistory(userid).setVisible(true);
    }//GEN-LAST:event_ViewTransHistoryActionPerformed

    private void bSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignOutActionPerformed
        this.setVisible(false);
        new UserLoginMenu().setVisible(true);
    }//GEN-LAST:event_bSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MakeBooking;
    private javax.swing.JLabel UserIDlabel;
    private javax.swing.JButton ViewBookingHistory;
    private javax.swing.JButton ViewCarDetails;
    private javax.swing.JButton ViewProfile;
    private javax.swing.JButton ViewTransHistory;
    private javax.swing.JButton bSignOut;
    private javax.swing.JLabel greetings;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
